// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sicomoro.Infrastructure.Persistence;

#nullable disable

namespace Sicomoro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SicomoroDbContext))]
    partial class SicomoroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sicomoro.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("text");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.AnuncioCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CtaTexto")
                        .HasColumnType("text");

                    b.Property<string>("CtaUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("PrecioTexto")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductoMaderaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductoMaderaId");

                    b.HasIndex("Publicado", "Orden");

                    b.ToTable("AnunciosCatalogo");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.CajaMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("PagoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CajaMovimientos");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CiNit")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Cobro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cobros");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CostoTransporte")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEstimadaLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OtrosCostos")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.CompraDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioCompra")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ProductoMaderaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoMaderaId");

                    b.ToTable("CompraDetalles");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.DocumentoVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DocumentosVenta");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductoMaderaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("UbicacionInterna")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductoMaderaId")
                        .IsUnique();

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductoMaderaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CobroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CobroId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Codigo = "clientes.leer",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Ver clientes"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Codigo = "ventas.confirmar",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Confirmar ventas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Codigo = "inventario.ajustar",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Ajustar inventario"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Codigo = "reportes.sensibles",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Ver reportes sensibles"
                        });
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.ProductoMadera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Ancho")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Calidad")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Espesor")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<decimal>("Largo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioCompra")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PrecioVentaSugerido")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("TipoMadera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProductosMadera");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Ancho = 4m,
                            Calidad = "A",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Espesor = 0m,
                            Estado = 1,
                            Largo = 2m,
                            NombreComercial = "Tajibo 2x4",
                            Observaciones = "Producto inicial",
                            PrecioCompra = 35m,
                            PrecioVentaSugerido = 55m,
                            StockMinimo = 10m,
                            TipoMadera = "Tajibo",
                            UnidadMedida = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Ancho = 0.3m,
                            Calidad = "A",
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Espesor = 0.05m,
                            Estado = 1,
                            Largo = 2.5m,
                            NombreComercial = "Cedro tabla",
                            Observaciones = "Producto inicial",
                            PrecioCompra = 45m,
                            PrecioVentaSugerido = 70m,
                            StockMinimo = 8m,
                            TipoMadera = "Cedro",
                            UnidadMedida = 2
                        });
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("LugarOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("TipoMadera")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Codigo = 1,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Codigo = 2,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vendedor"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Codigo = 3,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Encargado de inventario"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Codigo = 4,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cobrador"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Codigo = 5,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Dueno / gerente"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Codigo = 6,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Solo lectura"
                        });
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Transporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Camion")
                        .HasColumnType("text");

                    b.Property<string>("Chofer")
                        .HasColumnType("text");

                    b.Property<Guid?>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostoTransporte")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LugarOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transportes");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("CiNit")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@sicomoro.local",
                            Estado = 1,
                            Nombre = "Administrador Sicomoro",
                            PasswordHash = "pbkdf2:c2ljb21vcm8tc2VlZC0wMDE=:bitQBcTu2f0tf3B9103G2ZXgUAEMNTZh1ec+JQ0m0xI=",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.VentaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ProductoMaderaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoMaderaId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentaDetalles");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.AnuncioCatalogo", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.ProductoMadera", "ProductoMadera")
                        .WithMany()
                        .HasForeignKey("ProductoMaderaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductoMadera");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Cobro", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.Cliente", null)
                        .WithMany("Cobros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Compra", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.CompraDetalle", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.Compra", null)
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sicomoro.Domain.Entities.ProductoMadera", "ProductoMadera")
                        .WithMany()
                        .HasForeignKey("ProductoMaderaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoMadera");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Inventario", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.ProductoMadera", "ProductoMadera")
                        .WithMany()
                        .HasForeignKey("ProductoMaderaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoMadera");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.Cobro", null)
                        .WithMany("Pagos")
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Venta", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.VentaDetalle", b =>
                {
                    b.HasOne("Sicomoro.Domain.Entities.ProductoMadera", "ProductoMadera")
                        .WithMany()
                        .HasForeignKey("ProductoMaderaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sicomoro.Domain.Entities.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoMadera");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Cobros");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Cobro", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Sicomoro.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
